# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6772b29e0a37684c8b162bc098681891049704e84403b04be26e717078e923dce4afb49c390dee32e212896582a18214adcf5a946b014beb61fb1a5eb8c18fcc

test:
  secret_key_base: 4ca419ceaacf271837a8ed74f1a2f7b7e230f809c9206c7957ffb77171220b168e5b5addcf6e30a1be57577af0f6622fbb78539811dc53d01adffc21ae64c532

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
